[build]
  command = "echo \"window.__ENV__={FIREBASE_API_KEY:'$FIREBASE_API_KEY',EMAILJS_KEY:'$EMAILJS_KEY'};\" > env.js"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200